modelo:
  node_in_dim: 4
  edge_in_dim: 2
  hidden_dim_encoder: [128, 128]
  hidden_dim_messagepassing: [128, 128, 128, 128, 128, 128]
  hidden_dim_decoder: [128, 128]
  num_iters: 8
  batch_norm: false

procesamiento:
  pt_min: 0.57
  pt_max: 1000
  dtheta: pi/2 # 1.5707 # pi/2
  dphi: pi #3.1415 # pi
